name: Publish Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  # 👉 ini bikin bisa dijalankan manual lewat UI
permissions:
  contents: read
  packages: write
  id-token: write  # diperlukan untuk provenance

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          scope: '@jkt48'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # 👉 Publish to npmjs.org first, with provenance
      - name: Publish to npmjs.org with provenance
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --registry=https://registry.npmjs.org/ --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 👉 Then publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.SECRET_TOKEN }}" > .npmrc
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SECRET_TOKEN }}
